# @see https://docs.docker.com/compose/compose-file/compose-file-v3/#compose-and-docker-compatibility-matrix
version: "3.8"
services:
  # Postgres
  db:
    # Tribute Labs is using version 9.6 upstream
    image: postgres:9.6
    env_file:
      # Committed to source control for convience.
      - .env.dev
      # Adding as well, as we require API key(s) for dev. Not in source control.
      - .env
    # @see https://www.postgresql.org/docs/9.4/pgstatstatements.html
    command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
    volumes:
      - "db_vol:/var/lib/postgresql/data"
    ports:
      # Optional: override the `COMPOSE_HOST_DB_PORT` port in `.env`; defaults to `5432`
      - "${COMPOSE_HOST_DB_PORT:-5432}:5432"

  # App
  app:
    ##
    # Run an init inside the container that forwards signals (e.g. `SIGINT`) and reaps processes.
    #
    # @see https://docs.docker.com/compose/compose-file/compose-file-v3/#init
    ##
    init: true
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    env_file:
      # Committed to source control for convience.
      - .env.dev
      # Adding as well, as we require API key(s) for dev. Not in source control.
      - .env
    ports:
      # Optional: override the `COMPOSE_HOST_HTTP_API_PORT` port in `.env`; defaults to `3000`
      - "${COMPOSE_HOST_HTTP_API_PORT:-3000}:3000"
    volumes:
      - ./src:/home/node/app/src
      - ./prisma:/home/node/app/prisma
    depends_on:
      # Starts the `db` service first.
      # Does not wait for Postgres itself to be ready.
      - db
      - docker-host

  ##
  # This container will forward any traffic to your host machine.
  # For example, this is helpful to access a separate docker container/app
  # running from another `Dockerfile` or `docker-compose.yml`.
  #
  # @see https://github.com/qoomon/docker-host
  # @see https://sam-ngu.medium.com/connecting-to-docker-host-mysql-from-docker-container-linux-ubuntu-766e526542fd
  ##
  docker-host:
    image: qoomon/docker-host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: on-failure

volumes:
  db_vol: {}
