FROM node:16
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY tsconfig.json ./
COPY scripts scripts
COPY prisma prisma
COPY src src
COPY abi-types abi-types
# Make `wait-for-it` executable by the container
RUN ["chmod", "+x", "./scripts/wait-for-it.sh"]
# Make `wait-for-it` executable by the container
RUN ["chmod", "+x", "./scripts/dev-start.sh"]
# Wait for Postgres host:port to be open, then start the app
ENTRYPOINT ["./scripts/wait-for-it.sh", "db:5432", "--", "./scripts/dev-start.sh"]
