name: GKE Production Deployment

on:
  push:
    tags:
      - v*

env:
  REGISTRY_HOSTNAME: gcr.io
  IMAGE_NAME: thelao/tribute-discord-service
  GIT_COMMITTER_NAME: 'Pizza Dog'
  GIT_COMMITTER_EMAIL: 'dev@openlaw.io'
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  INFRA_REPO: openlawteam/lao-backends

jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check available environment variables
        uses: actions/checkout@v2

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v2.x

      # Use the GCP official setup action to auth, note that while mentioned in
      # the documentation, `service_account_email` value is not required if
      # using a JSON key versus legacy P12.
      #
      # Also the GCP_SA_KEY should be a base64 encoding of the JSON key file
      # obtained for a service account with appropriate permissions.
      - name: Set up Google Cloud Platform SDK and authenticate
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GPC_THELAO_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_THELAO_SA_KEY }}
          export_default_credentials: true

      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication. Needed if pushing images to GCR.io, etc.
      - name: Configure Docker for GCP credential helper
        run: gcloud --quiet auth configure-docker

      - name: Build and Publish Docker Image to GCR.io
        run: |
          export TAG=${{ env.GITHUB_REF_SLUG }}-${{ env.GITHUB_SHA_SHORT }}
          echo $TAG
          docker build -t "$REGISTRY_HOSTNAME"/${{ env.IMAGE_NAME }}:"$TAG" .
          docker push "$REGISTRY_HOSTNAME"/${{ env.IMAGE_NAME }}:"$TAG"
          docker tag "$REGISTRY_HOSTNAME"/${{ env.IMAGE_NAME }}:"$TAG" "$REGISTRY_HOSTNAME"/${{ env.IMAGE_NAME }}:main
          docker push "$REGISTRY_HOSTNAME"/${{ env.IMAGE_NAME }}:main
          
      - name: Checkout openlawteam/lao-backends repo
        uses: actions/checkout@v2
        with: 
          repository: ${{ env.INFRA_REPO }}
          token: ${{ secrets.PAT_OLBOT_PUB_REPOS_RW }}

      - name: Update the prod image tag
        run: |
          cd k8s/deployments/prod
          export TAG=${{ env.GITHUB_REF_SLUG }}-${{ env.GITHUB_SHA_SHORT }}
          echo $TAG
          ls
          sed -i "s|${{ env.IMAGE_NAME }}:main-.*|${{ env.IMAGE_NAME }}:$TAG|g" tribute-discord-deployment.yaml
          git config --local user.email ${{ env.GIT_COMMITTER_EMAIL }}
          git config --local user.name ${{ env.GIT_COMMITTER_NAME }}
          git commit -am "auto-release(prod): ${{ env.IMAGE_NAME }}:$TAG"
          git show

      - name: Push changes to openlawteam/lao-backends repo
        uses: ad-m/github-push-action@master
        with:
          repository: ${{ env.INFRA_REPO }}
          github_token: ${{ secrets.PAT_OLBOT_PUB_REPOS_RW }}
          branch: master
            